-- MySQL Script generated by MySQL Workbench
-- Wed Aug 30 21:05:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema institucion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema institucion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `institucion` DEFAULT CHARACTER SET utf8mb4 ;
USE `institucion` ;

-- -----------------------------------------------------
-- Table `institucion`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`grado` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `institucion`.`tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`tipo_documento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `institucion`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`docente` (
  `id` INT(11) NOT NULL,
  `id_tipodocumento` INT(11) NOT NULL,
  `numerodocumento` VARCHAR(45) NULL DEFAULT NULL,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_nacimiento` VARCHAR(45) NULL DEFAULT NULL,
  `asig_dictadas` INT(11) NULL DEFAULT NULL,
  `grado_escolaridad` VARCHAR(45) NULL DEFAULT NULL,
  `id_gradoresponsable` INT(11) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `fijo` VARCHAR(45) NULL DEFAULT NULL,
  `celular` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_docente_tipodocumento_idx` (`id_tipodocumento` ASC),
  INDEX `fk_docente_grado_idx` (`id_gradoresponsable` ASC),
  CONSTRAINT `fk_docente_grado`
    FOREIGN KEY (`id_gradoresponsable`)
    REFERENCES `institucion`.`grado` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_docente_tipodocumento`
    FOREIGN KEY (`id_tipodocumento`)
    REFERENCES `institucion`.`tipo_documento` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `institucion`.`asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`asignatura` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `id_docente` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_asignatura_docente_idx` (`id_docente` ASC),
  CONSTRAINT `fk_asignatura_docente`
    FOREIGN KEY (`id_docente`)
    REFERENCES `institucion`.`docente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `institucion`.`tipo_dane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`tipo_dane` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `institucion`.`dane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`dane` (
  `id` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `id_tipodane` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dane_tipodane_idx` (`id_tipodane` ASC),
  CONSTRAINT `fk_dane_tipodane`
    FOREIGN KEY (`id_tipodane`)
    REFERENCES `institucion`.`tipo_dane` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `institucion`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`estudiante` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_tipodocumento` INT(11) NOT NULL,
  `numerodocumento` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_nacimiento` VARCHAR(45) NULL DEFAULT NULL,
  `id_grado` INT(11) NOT NULL,
  `id_dane` INT(11) NOT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `fijo` VARCHAR(45) NULL DEFAULT NULL,
  `celular` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estudiante_tipodocumento_idx` (`id_tipodocumento` ASC),
  INDEX `fk_estudiante_grado_idx` (`id_grado` ASC),
  INDEX `fk_estudiante_dane_idx` (`id_dane` ASC),
  CONSTRAINT `fk_estudiante_dane`
    FOREIGN KEY (`id_dane`)
    REFERENCES `institucion`.`dane` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_estudiante_grado`
    FOREIGN KEY (`id_grado`)
    REFERENCES `institucion`.`grado` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_estudiante_tipodocumento`
    FOREIGN KEY (`id_tipodocumento`)
    REFERENCES `institucion`.`tipo_documento` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `institucion`.`estudiante_asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`estudiante_asignatura` (
  `nota` DOUBLE NULL DEFAULT NULL,
  `periodo` INT(11) NULL DEFAULT NULL,
  `id_estudiante` INT(11) NOT NULL,
  `id_asignatura` INT(11) NOT NULL,
  PRIMARY KEY (`id_estudiante`, `id_asignatura`),
  INDEX `fk_estudiante_idx` (`id_estudiante` ASC),
  INDEX `fk_asignatura_idx` (`id_asignatura` ASC),
  CONSTRAINT `fk_asignatura`
    FOREIGN KEY (`id_asignatura`)
    REFERENCES `institucion`.`asignatura` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_estudiante`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `institucion`.`estudiante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
